import { expect, test } from './fixtures'
import { seedWorkspace } from './harness/setup'

test('header navigation preserves destinations and focus across resize and text-size changes', async ({ page, aether }) => {
  const alice = await aether.member('alice')
  const repo = await aether.seedRepo('project')
  await seedWorkspace(alice, aether.server.addr, repo)
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto(alice.url)
  await page.evaluate(() => document.fonts.ready)

  const navigation = page.getByRole('navigation', { name: 'Main navigation' })
  const board = navigation.getByRole('button', { name: 'Board', exact: true })
  const swarms = navigation.getByRole('button', { name: 'Swarms', exact: true })
  const templates = navigation.getByRole('button', { name: 'Templates', exact: true })
  const more = navigation.getByRole('button', { name: 'More navigation' })
  const menu = page.getByRole('menu', { name: 'More navigation' })

  await templates.focus()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(more).toBeFocused()
  await expect(board).toBeVisible()
  await expect(swarms).toBeVisible()
  await expect(templates).toBeHidden()

  await more.press('Enter')
  await menu.getByRole('menuitem', { name: 'Templates', exact: true }).click()
  await expect(menu).toBeHidden()
  await expect(page.getByRole('heading', { level: 1, name: 'Templates', exact: true })).toBeFocused()

  await more.press('Enter')
  await menu.getByRole('menuitem', { name: 'Agents', exact: true }).focus()
  await page.setViewportSize({ width: 1280, height: 900 })
  await expect(menu).toBeHidden()
  await expect(templates).toBeFocused()
  await expect(more).toBeHidden()

  await page.setViewportSize({ width: 768, height: 900 })
  await expect(templates).toBeVisible()
  await page.getByRole('navigation', { name: 'Aether' }).getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByLabel('Text size', { exact: true }).click()
  await page.getByRole('option', { name: 'Larger', exact: true }).click()
  await expect(templates).toBeHidden()
  await expect(board).toBeVisible()
  await expect(swarms).toBeVisible()
  await more.press('Enter')
  await expect(menu.getByRole('menuitem', { name: 'Templates', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(more).toBeFocused()

  await page.getByLabel('Text size', { exact: true }).click()
  await page.getByRole('option', { name: 'Default', exact: true }).click()
  await expect(templates).toBeVisible()
  await expect(more).toBeHidden()
})
