// Import every route file once, for its registerRoute side effect. New views
// (the board, terminal, diffs, team surfaces) add one line here.
import '@/routes/agents'
import '@/routes/board'
import '@/routes/configuration'
import '@/routes/devices'
import '@/routes/environment'
import '@/routes/files'
import '@/routes/members'
import '@/routes/missions'
import '@/routes/onboarding'
import '@/routes/overview'
import '@/routes/run'
import '@/routes/run-sync'
import '@/routes/workspace'
import '@/routes/settings'
import '@/routes/team'
import '@/routes/templates'
import '@/routes/workspaces'

export { lookupRoute, registerRoute, type RouteProps } from '@/routes/registry'
