package memberhome

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"image/gif"
	"image/jpeg"
	"image/png"
	"io"
	"io/fs"
	"os"
	"regexp"

	"github.com/3xDevOps/Aether/internal/domain"
	"golang.org/x/image/webp"
)

const (
	terminalImageDir       = ".aether/terminal-images"
	terminalImageNameBytes = 16
)

var imageNamePattern = regexp.MustCompile(`^image-[0-9a-f]{32}\.(png|jpg|gif|webp)$`)

// ValidImageName accepts only server-generated image basenames.
func ValidImageName(name string) bool {
	return imageNamePattern.MatchString(name)
}

// ValidateImage identifies supported image bytes and validates their headers.
// It deliberately uses DecodeConfig, matching upload validation without
// allocating a decoded pixel buffer.
func ValidateImage(data []byte) (extension, mimeType string, err error) {
	if len(data) == 0 {
		return "", "", fmt.Errorf("image content is empty")
	}
	if len(data) > domain.MaxImageBytes {
		return "", "", fmt.Errorf("image exceeds the 8 MiB limit")
	}
	switch {
	case bytes.HasPrefix(data, []byte("\x89PNG\r\n\x1a\n")):
		if _, err := png.DecodeConfig(bytes.NewReader(data)); err != nil {
			return "", "", fmt.Errorf("invalid PNG image: %w", err)
		}
		return ".png", "image/png", nil
	case len(data) >= 3 && data[0] == 0xff && data[1] == 0xd8 && data[2] == 0xff:
		if _, err := jpeg.DecodeConfig(bytes.NewReader(data)); err != nil {
			return "", "", fmt.Errorf("invalid JPEG image: %w", err)
		}
		return ".jpg", "image/jpeg", nil
	case len(data) >= 6 && (bytes.Equal(data[:6], []byte("GIF87a")) || bytes.Equal(data[:6], []byte("GIF89a"))):
		if _, err := gif.DecodeConfig(bytes.NewReader(data)); err != nil {
			return "", "", fmt.Errorf("invalid GIF image: %w", err)
		}
		return ".gif", "image/gif", nil
	case len(data) >= 12 && bytes.Equal(data[:4], []byte("RIFF")) && bytes.Equal(data[8:12], []byte("WEBP")):
		if _, err := webp.DecodeConfig(bytes.NewReader(data)); err != nil {
			return "", "", fmt.Errorf("invalid WebP image: %w", err)
		}
		return ".webp", "image/webp", nil
	default:
		return "", "", fmt.Errorf("unsupported or invalid image format")
	}
}

// ReadImage reads a generated image from an existing persistent home. All
// components are opened without following links; MIME comes from the bytes.
func (m *Manager) ReadImage(member domain.MemberID, name string) ([]byte, string, error) {
	if !ValidImageName(name) {
		return nil, "", fmt.Errorf("memberhome: invalid image name %q", name)
	}
	root, err := m.openExistingHome(member)
	if err != nil {
		return nil, "", err
	}
	defer func() { _ = root.Close() }()
	f, info, err := openRegular(root, terminalImageDir+"/"+name)
	if err != nil {
		return nil, "", fmt.Errorf("memberhome: open image for %q: %w", member, err)
	}
	defer func() { _ = f.Close() }()
	data, err := readImageFile(f, info)
	if err != nil {
		return nil, "", fmt.Errorf("memberhome: read image for %q: %w", member, err)
	}
	_, mimeType, err := ValidateImage(data)
	if err != nil {
		return nil, "", fmt.Errorf("memberhome: invalid image for %q: %w", member, err)
	}
	return data, mimeType, nil
}

func readImageFile(f *os.File, info fs.FileInfo) ([]byte, error) {
	if info.Size() > domain.MaxImageBytes {
		return nil, fmt.Errorf("image exceeds the 8 MiB limit")
	}
	// Read one extra byte to reject files that grow after the descriptor stat.
	data, err := io.ReadAll(io.LimitReader(f, domain.MaxImageBytes+1))
	if err != nil {
		return nil, err
	}
	if len(data) > domain.MaxImageBytes {
		return nil, fmt.Errorf("image exceeds the 8 MiB limit")
	}
	return data, nil
}

// SaveImage writes one already-decoded terminal image into the member's
// persistent home. The destination is generated by the server and all path
// operations stay confined to that home; callers receive a home-relative path
// to combine with the target container's HOME.
func (m *Manager) SaveImage(member domain.MemberID, extension string, data []byte) (string, error) {
	if len(data) == 0 || len(data) > domain.MaxImageBytes {
		return "", fmt.Errorf("memberhome: image is empty or exceeds %d bytes", domain.MaxImageBytes)
	}
	switch extension {
	case ".png", ".jpg", ".gif", ".webp":
	default:
		return "", fmt.Errorf("memberhome: unsupported image extension %q", extension)
	}

	root, err := m.openHome(member)
	if err != nil {
		return "", err
	}
	defer func() { _ = root.Close() }()
	for _, dir := range []string{".aether", terminalImageDir} {
		if err := ensureDir(root, dir); err != nil {
			return "", fmt.Errorf("memberhome: prepare image directory %q for %q: %w", dir, member, err)
		}
	}

	for range 10 {
		var suffix [terminalImageNameBytes]byte
		if _, err := rand.Read(suffix[:]); err != nil {
			return "", fmt.Errorf("memberhome: generate image name for %q: %w", member, err)
		}
		name := terminalImageDir + "/image-" + hex.EncodeToString(suffix[:]) + extension
		if err := writeNew(root, name, data, 0o600); err != nil {
			if errors.Is(err, fs.ErrExist) {
				continue
			}
			_ = root.RemoveAll(name)
			return "", fmt.Errorf("memberhome: write image for %q: %w", member, err)
		}
		return name, nil
	}
	return "", fmt.Errorf("memberhome: generate unique image name for %q", member)
}
