package memberhome

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"

	"github.com/3xDevOps/Aether/internal/domain"
)

const (
	terminalImageDir       = ".aether/terminal-images"
	maxTerminalImageBytes  = 8 << 20
	terminalImageNameBytes = 16
)

// SaveImage writes one already-decoded terminal image into the member's
// persistent home. The destination is generated by the server and all path
// operations stay confined to that home; callers receive a home-relative path
// to combine with the target container's HOME.
func (m *Manager) SaveImage(member domain.MemberID, extension string, data []byte) (string, error) {
	if len(data) == 0 || len(data) > maxTerminalImageBytes {
		return "", fmt.Errorf("memberhome: image is empty or exceeds %d bytes", maxTerminalImageBytes)
	}
	switch extension {
	case ".png", ".jpg", ".gif", ".webp":
	default:
		return "", fmt.Errorf("memberhome: unsupported image extension %q", extension)
	}

	root, err := m.openHome(member)
	if err != nil {
		return "", err
	}
	defer func() { _ = root.Close() }()
	for _, dir := range []string{".aether", terminalImageDir} {
		if err := ensureDir(root, dir); err != nil {
			return "", fmt.Errorf("memberhome: prepare image directory %q for %q: %w", dir, member, err)
		}
	}

	for range 10 {
		var suffix [terminalImageNameBytes]byte
		if _, err := rand.Read(suffix[:]); err != nil {
			return "", fmt.Errorf("memberhome: generate image name for %q: %w", member, err)
		}
		name := terminalImageDir + "/image-" + hex.EncodeToString(suffix[:]) + extension
		if err := writeNew(root, name, data, 0o600); err != nil {
			if errors.Is(err, fs.ErrExist) {
				continue
			}
			_ = root.RemoveAll(name)
			return "", fmt.Errorf("memberhome: write image for %q: %w", member, err)
		}
		if err := chownLikeHome(root, ".aether", terminalImageDir, name); err != nil {
			_ = root.RemoveAll(name)
			return "", fmt.Errorf("memberhome: hand image to home owner for %q: %w", member, err)
		}
		return name, nil
	}
	return "", fmt.Errorf("memberhome: generate unique image name for %q", member)
}
